branch-defaults:
  default:
    environment: null
global:
  application_name: simplecart
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: null
